# Generated by Django 5.0.4 on 2024-04-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_blogpost_created_at_alter_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='date',
        ),
    ]
